[package]
name = "champr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.14.0"
confy = "0.4.0"
serde = { version = "1.0.132", features = ["derive"] }
